---
- name: Add Tower inventory, update, or destroy inventory
  tower_inventory:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    organization: "{{ item.organization }}"
    state: present
  with_items: "{{ tower_inventories }}"

- name: registering ID of inventory
  shell: tower-cli inventory create -n "{{item.name | quote }}" --organization "{{item.organization | quote }}" | grep "{{item.name | quote }}" | awk '{print $1;}'
  register: command_output
  with_items: "{{ tower_inventories }}"

- debug: msg="{{command_output}}"

- name: Add source to inventry project
  shell: tower-cli inventory_source create -n "{{item.name | quote }}" --inventory "{{command_output.stdout | quote }}" --source-project "{{item.project | quote }}" --source "{{item.source | quote }}" --overwrite --overwrite-vars
  with_items: "{{ tower_inventories }}"  

- name: Update Inventory for tower-inventory
  command: >
    tower-cli inventory batch_update
      --name "{{ item.name }}"
      --wait
      "{{ tower_cli_verbosity }}"
  with_items: "{{ tower_inventories }}"
