---
- name: Install Projects - install packages
  yum:
    name: "{{ item.package }}"
    state: present
  become: true
  when: item.kind == "install"
  with_items: "{{ tower_packages | default([]) }}"