---
- name: Install/Provision Projects
  tower_project:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    state: present
    scm_credential: "{{ item.scm_credential }}"
    organization: "{{ item.organization }}"
    scm_type: "{{ item.scm_type }}"
    local_path: "{{ item.local_path | default(None) }}"
    scm_clean: "{{ item.clean | default(None) }}"
    scm_update_on_launch: "{{ item.update_on_launch | default(None) }}"
    scm_delete_on_update: "{{ item.delete_on_update | default(None) }}"
    scm_url: "{{ item.url | default(None) }}"
    scm_branch: "{{ item.branch | default(None) }}"
  with_items: "{{ tower_projects | default([]) }}"

- name: Provision Projects - update
  command: >
    tower-cli project update
      --name "{{ item.name }}"
      --wait
      "{{ tower_cli_verbosity }}"
  when: item.kind == "provision"
  with_items: "{{ tower_projects | default([]) }}"
...
