---
- include_tasks: projects/provision_and_configure.yml
  when: tower_project_provision_and_configure_config|bool == true
- include_tasks: projects/install.yml
  when: tower_project_install_config|bool == true
...
